apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    generated-by: convert_to_universal_chart.py
  name: demo-web-microservices
  namespace: argocd
spec:
  generators:
  - git:
      files:
      - path: demo-web/releases/*.yaml
      repoURL: https://git.example.com/gitops/microservices-values.git
      revision: main
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: '0'
      labels:
        managed-by: universal-chart-converter
        namespace: demo-web
      name: demo-web-{{release}}
    spec:
      destination:
        namespace: demo-web
        server: https://kubernetes.default.svc
      ignoreDifferences:
      - group: apps
        jqPathExpressions: &id001
        - .spec.template.spec.securityContext.runAsUser
        - .spec.template.spec.securityContext.runAsGroup
        - .spec.template.spec.securityContext.fsGroup
        - .spec.template.spec.securityContext.seLinuxOptions
        - .spec.template.spec.containers[]?.securityContext.runAsUser
        - .spec.template.spec.containers[]?.securityContext.capabilities
        kind: Deployment
      - group: apps
        jqPathExpressions:
        - .spec.template.spec.securityContext.runAsUser
        - .spec.template.spec.securityContext.runAsGroup
        - .spec.template.spec.securityContext.fsGroup
        - .spec.template.spec.securityContext.seLinuxOptions
        - .spec.template.spec.containers[]?.securityContext.runAsUser
        - .spec.template.spec.containers[]?.securityContext.capabilities
        - .spec.volumeClaimTemplates
        kind: StatefulSet
      - group: apps
        jqPathExpressions: *id001
        kind: DaemonSet
      - group: ''
        jsonPointers:
        - /secrets
        - /imagePullSecrets
        kind: ServiceAccount
      project: default
      sources:
      - helm:
          valueFiles:
          - $values/defaults.yaml
          - $values/demo-web/defaults.yaml
          - $values/demo-web/values/{{release}}-values.yaml
          - $values/demo-web/values-minimal/{{release}}-values-minimal.yaml
        path: Universal-chart
        repoURL: https://git.example.com/gitops/universal-chart.git
        targetRevision: main
      - ref: values
        repoURL: https://git.example.com/gitops/microservices-values.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
