apiVersion: batch/v1
kind: Job
metadata:
  name: demo-jobs-migrate
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: busybox:1.36
          command: ["/bin/sh", "-c"]
          args: ["echo running one-off migration; sleep 2; echo done"]
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 50m
              memory: 32Mi
