apiVersion: v1
kind: ServiceAccount
metadata:
  name: identity-svc-scanner-b-sa
  namespace: identity-svc
  labels:
    app.kubernetes.io/name: identity-svc-scanner-b-sa
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"redacted"}'
  uid: 69674c47-474b-40cc-b9b2-ef144c3fe9f0
  resourceVersion: '8444488'
  generation: 1
  creationTimestamp: '2026-02-23T08:11:22Z'
  managedFields:
  - manager: kubectl-client-side-apply
    operation: Update
    apiVersion: v1
    time: '2026-02-23T08:11:22Z'
    fieldsType: FieldsV1
automountServiceAccountToken: true
secrets:
- name: identity-svc-scanner-b-sa-token-a1b2c
- name: identity-svc-scanner-b-sa-dockercfg-x9z8y
imagePullSecrets:
- name: identity-svc-scanner-b-sa-dockercfg-x9z8y
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: audit-role
  namespace: identity-svc
  labels:
    app.kubernetes.io/name: audit-role
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"redacted"}'
  uid: 63036afd-5883-40c4-a33a-65f82030591d
  resourceVersion: '6697509'
  generation: 9
  creationTimestamp: '2026-06-14T08:11:22Z'
  managedFields:
  - manager: kubectl-client-side-apply
    operation: Update
    apiVersion: v1
    time: '2026-06-14T08:11:22Z'
    fieldsType: FieldsV1
rules:
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: identity-svc-scanner-b-audit-rb
  namespace: identity-svc
  labels:
    app.kubernetes.io/name: identity-svc-scanner-b-audit-rb
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"redacted"}'
  uid: af412939-f783-4eb5-8fc6-b1e748849228
  resourceVersion: '4138756'
  generation: 4
  creationTimestamp: '2025-12-08T08:11:22Z'
  managedFields:
  - manager: kubectl-client-side-apply
    operation: Update
    apiVersion: v1
    time: '2025-12-08T08:11:22Z'
    fieldsType: FieldsV1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: audit-role
subjects:
- kind: ServiceAccount
  name: identity-svc-scanner-b-sa
  namespace: identity-svc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-svc-scanner-b-audit-settings
  namespace: identity-svc
  labels:
    app.kubernetes.io/name: identity-svc-scanner-b-audit-settings
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"redacted"}'
  uid: 22a59250-79da-4391-8d7c-c09180375a79
  resourceVersion: '6020597'
  generation: 1
  creationTimestamp: '2025-10-05T08:11:22Z'
  managedFields:
  - manager: kubectl-client-side-apply
    operation: Update
    apiVersion: v1
    time: '2025-10-05T08:11:22Z'
    fieldsType: FieldsV1
data:
  AUDIT_ENABLED: 'true'
