apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-svc-scanner-a-sa
  namespace: analytics-svc
  labels:
    app.kubernetes.io/name: analytics-svc-scanner-a-sa
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"redacted"}'
  uid: 8519f2c4-7230-4580-9f07-d76417fe9c01
  resourceVersion: '9920882'
  generation: 5
  creationTimestamp: '2025-12-24T08:11:30Z'
  managedFields:
  - manager: kubectl-client-side-apply
    operation: Update
    apiVersion: v1
    time: '2025-12-24T08:11:30Z'
    fieldsType: FieldsV1
automountServiceAccountToken: true
secrets:
- name: analytics-svc-scanner-a-sa-token-a1b2c
- name: analytics-svc-scanner-a-sa-dockercfg-x9z8y
imagePullSecrets:
- name: analytics-svc-scanner-a-sa-dockercfg-x9z8y
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: audit-role
  namespace: analytics-svc
  labels:
    app.kubernetes.io/name: audit-role
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"redacted"}'
  uid: 87e7da62-028f-4e3e-b807-baca0f7f6c4c
  resourceVersion: '9094347'
  generation: 7
  creationTimestamp: '2026-03-19T08:11:30Z'
  managedFields:
  - manager: kubectl-client-side-apply
    operation: Update
    apiVersion: v1
    time: '2026-03-19T08:11:30Z'
    fieldsType: FieldsV1
rules:
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: analytics-svc-scanner-a-audit-rb
  namespace: analytics-svc
  labels:
    app.kubernetes.io/name: analytics-svc-scanner-a-audit-rb
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"redacted"}'
  uid: 8bb72680-c2bf-4465-9c08-ab69a446f788
  resourceVersion: '6234489'
  generation: 10
  creationTimestamp: '2025-10-14T08:11:30Z'
  managedFields:
  - manager: kubectl-client-side-apply
    operation: Update
    apiVersion: v1
    time: '2025-10-14T08:11:30Z'
    fieldsType: FieldsV1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: audit-role
subjects:
- kind: ServiceAccount
  name: analytics-svc-scanner-a-sa
  namespace: analytics-svc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-svc-scanner-a-audit-settings
  namespace: analytics-svc
  labels:
    app.kubernetes.io/name: analytics-svc-scanner-a-audit-settings
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"redacted"}'
  uid: 6bcc262a-3f02-4fe1-bf7b-24abcd3d0dd4
  resourceVersion: '6768174'
  generation: 4
  creationTimestamp: '2026-03-11T08:11:30Z'
  managedFields:
  - manager: kubectl-client-side-apply
    operation: Update
    apiVersion: v1
    time: '2026-03-11T08:11:30Z'
    fieldsType: FieldsV1
data:
  AUDIT_ENABLED: 'true'
