#!/usr/bin/env python3
"""
convert_to_universal_chart.py
==============================
Converts raw Kubernetes/OpenShift manifests dumped per-namespace/per-microservice

    namespaces/<namespace>/<microservice>.yaml   (multi-document)
    namespaces/<namespace>/shared.yaml           (multi-document, optional)

into:

    1. Two Universal Helm Chart values files PER microservice:
         <microservice>-values.yaml           (comprehensive - everything
                                                EXCEPT image tag & literal env)
         <microservice>-values-minimal.yaml   (image tag + literal env ONLY -
                                                exclusively here, not duplicated
                                                in the comprehensive file)

    2. One namespace-shared "release" (workload.type: none) that owns any
       resources living in shared.yaml, so they are never double-declared
       (and therefore never double-owned) by every microservice that uses them.

    3. One ArgoCD ApplicationSet PER namespace that fans out over every
       microservice directory and deploys the Universal Chart with the two
       values files layered (comprehensive base -> minimal override).

    4. One cluster-scoped "shared" values file + Application for anything
       that is cluster-scoped in Kubernetes (ClusterRole, ClusterRoleBinding,
       StorageClass, PersistentVolume, SecurityContextConstraints) — these can
       never be safely owned by more than one Helm release, so they are
       deduplicated globally across the *entire* run, not just per namespace.

    5. (Unless --skip-verify) Proof that the output is actually safe to
       apply: every generated release is rendered for real with `helm
       template` and checked, on the RENDERED manifests (not just the values
       files), that no two releases claim the same (kind, namespace, name)
       for a namespaced resource and no two releases in the whole run claim
       the same (kind, name) for a cluster-scoped one. This is the same
       static analysis as steps 1-4 above, just verified against the real
       chart instead of trusted blindly — pass --chart to point at a
       non-default Universal Chart location, or --skip-verify to skip it
       (e.g. if `helm` isn't installed, or for a quick dry run).

Conflict-free by construction
------------------------------
Several kinds render with their RAW map key as the Kubernetes resource name
(no release-name prefix) per the Universal Chart's templates: ConfigMap,
Secret, PersistentVolumeClaim, NetworkPolicy, Role, RoleBinding, Route (extra),
Service (extra), SecretStore, ExternalSecret and (cluster-scoped) ClusterRole,
ClusterRoleBinding, StorageClass, PersistentVolume, SecurityContextConstraints,
ClusterSecretStore. Those are exactly the ones that can collide once multiple
microservices/namespaces are deployed as separate Helm releases. This script
resolves collisions deterministically:

  * A name first declared in shared.yaml is "owned" by the namespace-shared
    release. Any microservice that also happens to (re)declare it locally
    drops its own copy and simply references the shared name — no ownership
    fight, no "already exists" error.
  * A name first declared by microservice A, and later declared independently
    (by coincidence, not via shared.yaml) by microservice B, is automatically
    renamed to "<B>-<name>" for B, and every reference to it inside B's own
    values (env, envFrom, volumes, rbac roleRef/subjects) is rewritten to
    match. This is logged, not silently swallowed.
  * Cluster-scoped kinds are deduplicated by (kind, name) across the whole
    run. If two different namespaces define the same name with different
    content, the first one wins and the conflict is written to the report
    for a human to resolve — cluster-scoped identity can't be safely renamed
    (StorageClass/SCC names are referenced by exact string elsewhere).

Usage
-----
    python convert_to_universal_chart.py --input namespaces --output output

    # Point --chart at the Universal Chart if it isn't at the default
    # relative location, or pass --skip-verify to skip the helm-template
    # render-verification step entirely (e.g. helm isn't installed):
    python convert_to_universal_chart.py --input namespaces --output output \\
        --chart ../Universal-chart

See README.md for the full end-to-end verification workflow.
"""
from __future__ import annotations

import argparse
import copy
import hashlib
import json
import re
import subprocess
import sys
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

import yaml

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Resources that are transient / controller-owned / generated by the cluster
# itself. A raw dump from `oc get all -o yaml` typically includes these; they
# are not desired-state and must never be converted.
TRANSIENT_KINDS = {
    "ReplicaSet", "Pod", "Endpoints", "EndpointSlice", "Event",
    "ControllerRevision", "Binding",
}

CLUSTER_SCOPED_KINDS = {
    "ClusterRole", "ClusterRoleBinding", "StorageClass",
    "PersistentVolume", "SecurityContextConstraints", "ClusterSecretStore",
}

WORKLOAD_KINDS = {"Deployment", "StatefulSet", "DaemonSet"}

# Kinds whose Universal Chart template renders the resource name as the RAW
# values map-key (no `<release>-` prefix) — see templates/*.yaml. These are
# exactly the ones the NamespaceRegistry / ClusterRegistry must dedupe.
NS_RAW_NAME_KINDS = [
    "ConfigMap", "Secret", "PersistentVolumeClaim", "NetworkPolicy",
    "Role", "RoleBinding", "ServiceAccount", "Route", "Service",
    "SecretStore", "ExternalSecret",
]

AUTO_SA_SECRET_RE = re.compile(r".+-(dockercfg|token)-[a-z0-9]{5}$")

# Directory/release names must be valid Helm release names & K8s resource
# names (lowercase alphanumeric + '-', no leading underscore) — hence "shared"
# rather than "_shared" on disk, even though the internal registry sentinel
# owner label stays "_shared" (never itself written to a path).
SHARED_DIR_NAME = "shared"
CLUSTER_SHARED_DIR_NAME = "cluster-shared"

# Output layout: <output>/<namespace>/{values,values-minimal}/<microservice>-values*.yaml
# Full and minimal values are FLAT files (no per-microservice subdirectory)
# in two PARALLEL trees under each namespace. cluster-shared is treated like
# a namespace one level up (<output>/cluster-shared/values/, no
# values-minimal counterpart, and no releases/ pointer since it's a single
# release with no fan-out).
#
# releases/<microservice>.yaml is a tiny (one-line) pointer file — NOT a
# values file — written purely so an ArgoCD ApplicationSet git "files"
# generator can enumerate microservices without needing a directory per
# release. Its only content is {release: <microservice>}; the actual values
# live at the flat paths above.
VALUES_DIR_NAME = "values"
VALUES_MINIMAL_DIR_NAME = "values-minimal"
RELEASES_DIR_NAME = "releases"
NON_NAMESPACE_OUTPUT_DIRS = {"applicationsets", "report"}

VOLATILE_ANNOTATION_PREFIXES = (
    "kubectl.kubernetes.io/last-applied-configuration",
    "kubernetes.io/created-by",
    "openshift.io/generated-by",
    "openshift.io/deployment.phase",
    "image.openshift.io/triggers",
    "openshift.io/host.generated",
)

VOLATILE_METADATA_KEYS = (
    "creationTimestamp", "resourceVersion", "uid", "generation",
    "selfLink", "managedFields", "namespace", "ownerReferences",
    "generateName", "finalizers",
)


# ---------------------------------------------------------------------------
# YAML I/O helpers
# ---------------------------------------------------------------------------

def load_multidoc(path: Path) -> list[dict]:
    text = path.read_text(encoding="utf-8")
    return [d for d in yaml.safe_load_all(text) if d]


def dump_yaml(data: Any) -> str:
    if not data:
        return "{}\n"
    return yaml.safe_dump(data, sort_keys=True, default_flow_style=False, width=100)


# ---------------------------------------------------------------------------
# Sanitization
# ---------------------------------------------------------------------------

def clean_annotations(ann: Optional[dict]) -> dict:
    if not ann:
        return {}
    return {k: v for k, v in ann.items() if not k.startswith(VOLATILE_ANNOTATION_PREFIXES)}


def filter_transient(docs: list[dict]) -> list[dict]:
    """Drop controller-owned / generated objects that are not desired state."""
    out = []
    for d in docs:
        kind = d.get("kind")
        if kind in TRANSIENT_KINDS:
            continue
        if kind == "Job":
            owners = (d.get("metadata") or {}).get("ownerReferences") or []
            if any(o.get("kind") == "CronJob" for o in owners):
                continue  # a CronJob-spawned Job instance, not standalone desired state
        out.append(d)
    return out


def sanitize_object(doc: dict) -> dict:
    """Strip OpenShift/Kubernetes runtime & cluster-specific noise."""
    doc = copy.deepcopy(doc)
    doc.pop("status", None)

    meta = doc.get("metadata", {}) or {}
    for key in VOLATILE_METADATA_KEYS:
        meta.pop(key, None)
    ann = clean_annotations(meta.get("annotations"))
    if ann:
        meta["annotations"] = ann
    else:
        meta.pop("annotations", None)
    doc["metadata"] = meta

    kind = doc.get("kind")
    spec = doc.get("spec")
    if kind == "Service" and isinstance(spec, dict):
        if spec.get("clusterIP") != "None":
            spec.pop("clusterIP", None)
        for k in ("clusterIPs", "ipFamilies", "ipFamilyPolicy", "internalTrafficPolicy"):
            spec.pop(k, None)
    if kind == "Route" and isinstance(spec, dict):
        spec.pop("host", None) if spec.get("host", "").endswith(".apps.cluster-generated.local") else None

    return doc


def is_auto_sa_secret(doc: dict) -> bool:
    if doc.get("type") in ("kubernetes.io/service-account-token", "kubernetes.io/dockercfg"):
        return True
    name = (doc.get("metadata") or {}).get("name", "")
    return bool(AUTO_SA_SECRET_RE.match(name))


def content_hash(doc: dict) -> str:
    """Identity hash ignoring cosmetic metadata (labels/annotations)."""
    d = copy.deepcopy(doc)
    meta = d.get("metadata", {})
    meta.pop("labels", None)
    meta.pop("annotations", None)
    return hashlib.sha256(json.dumps(d, sort_keys=True, default=str).encode()).hexdigest()[:16]


def split_image(image: str) -> tuple[str, str]:
    if not image:
        return "", ""
    if "@" in image:
        return image.split("@")[0], ""
    if ":" in image:
        repo, _, maybe_tag = image.rpartition(":")
        if "/" not in maybe_tag:
            return repo, maybe_tag
    return image, ""


# ---------------------------------------------------------------------------
# Name registries — this is the conflict-free core of the converter
# ---------------------------------------------------------------------------

class NamespaceRegistry:
    """Dedupes raw-named (release-unprefixed) resources within one namespace."""

    def __init__(self, namespace: str):
        self.namespace = namespace
        self.claims: dict[tuple[str, str], dict] = {}

    def claim(self, kind: str, name: str, content_h: str, owner: str):
        """Returns (final_name, action, note). action in own|reference_shared|renamed."""
        key = (kind, name)
        existing = self.claims.get(key)

        if existing is None:
            self.claims[key] = {"owner": owner, "hash": content_h}
            return name, "own", None

        if existing["owner"] == owner:
            return name, "own", None

        if existing["owner"] == "_shared":
            return name, "reference_shared", (
                f"{kind}/{name}: already owned by the namespace-shared release; "
                f"'{owner}' dropped its duplicate declaration and now references the shared resource"
            )

        if owner == "_shared":
            self.claims[key] = {"owner": "_shared", "hash": content_h}
            return name, "own", (
                f"{kind}/{name}: promoted to namespace-shared even though microservice "
                f"'{existing['owner']}' already privately declared it — verify '{existing['owner']}' "
                f"is updated to reference the shared copy instead of owning its own"
            )

        new_name = f"{owner}-{name}"
        same = existing["hash"] == content_h
        self.claims[(kind, new_name)] = {"owner": owner, "hash": content_h}
        return new_name, "renamed", (
            f"{kind}/{name}: name collision between microservices '{existing['owner']}' and "
            f"'{owner}' in namespace '{self.namespace}' ({'identical' if same else 'DIFFERING'} "
            f"content) -> renamed '{owner}' copy to '{new_name}'"
        )


class ClusterRegistry:
    """Dedupes cluster-scoped kinds globally, across every namespace in the run."""

    def __init__(self):
        self.claims: dict[tuple[str, str], dict] = {}

    def claim(self, kind: str, name: str, content_h: str, namespace: str, microservice: str):
        """Returns (should_emit, note)."""
        key = (kind, name)
        existing = self.claims.get(key)
        if existing is None:
            self.claims[key] = {"first_owner": (namespace, microservice), "hash": content_h}
            return True, None
        if existing["hash"] == content_h:
            return False, None
        return False, (
            f"{kind}/{name}: cluster-scoped resource defined with DIFFERING content in "
            f"{existing['first_owner']} and ({namespace}, {microservice}) — keeping the first "
            f"definition; the second occurrence was skipped and needs manual review"
        )


# ---------------------------------------------------------------------------
# Per-microservice conversion context
# ---------------------------------------------------------------------------

@dataclass
class MicroserviceContext:
    namespace: str
    name: str
    values: dict = field(default_factory=dict)
    extra_deploy: list = field(default_factory=list)
    warnings: list = field(default_factory=list)
    name_map: dict = field(default_factory=lambda: defaultdict(dict))
    claim_actions: dict = field(default_factory=lambda: defaultdict(dict))
    saw_workload: bool = False
    saw_service: bool = False
    primary_sa_set: bool = False
    primary_route_set: bool = False
    primary_service_set: bool = False
    # Full (untrimmed) image/env, kept only so build_minimal_values can pull
    # the tag / literal env vars out of them — ctx.values["image"]/["env"]
    # themselves deliberately EXCLUDE tag / literal env (see
    # handle_main_container) so those aren't duplicated in both files.
    full_image: dict = field(default_factory=dict)
    full_env: dict = field(default_factory=dict)


def env_list_to_map(env_list) -> dict:
    out = {}
    for e in env_list or []:
        name = e["name"]
        out[name] = {k: v for k, v in e.items() if k != "name"}
    return out


def envfrom_list_to_map(envfrom_list) -> dict:
    out = {}
    for e in envfrom_list or []:
        if "configMapRef" in e:
            ref, typ = e["configMapRef"], "configMapRef"
        elif "secretRef" in e:
            ref, typ = e["secretRef"], "secretRef"
        else:
            continue
        entry = {"type": typ}
        if ref.get("optional") is not None:
            entry["optional"] = ref["optional"]
        out[ref["name"]] = entry
    return out


def ports_list_to_map(ports_list) -> dict:
    out = {}
    for p in ports_list or []:
        name = p.get("name") or f"port-{p['containerPort']}"
        out[name] = {k: v for k, v in p.items() if k != "name"}
    return out


def named_list_to_map(items) -> dict:
    out = {}
    for it in items or []:
        name = it["name"]
        out[name] = {k: v for k, v in it.items() if k != "name"}
    return out


def remap_env(env_map: dict, ctx: MicroserviceContext) -> dict:
    for _, v in env_map.items():
        vf = v.get("valueFrom") or {}
        if "configMapKeyRef" in vf:
            n = vf["configMapKeyRef"].get("name")
            if n:
                vf["configMapKeyRef"]["name"] = ctx.name_map["ConfigMap"].get(n, n)
        if "secretKeyRef" in vf:
            n = vf["secretKeyRef"].get("name")
            if n:
                vf["secretKeyRef"]["name"] = ctx.name_map["Secret"].get(n, n)
    return env_map


def remap_envfrom(ef_map: dict, ctx: MicroserviceContext) -> dict:
    out = {}
    for name, entry in ef_map.items():
        kind = "ConfigMap" if entry.get("type") == "configMapRef" else "Secret"
        out[ctx.name_map[kind].get(name, name)] = entry
    return out


def remap_volumes(vol_map: dict, ctx: MicroserviceContext) -> dict:
    for _, entry in vol_map.items():
        if "persistentVolumeClaim" in entry and entry["persistentVolumeClaim"].get("claimName"):
            n = entry["persistentVolumeClaim"]["claimName"]
            entry["persistentVolumeClaim"]["claimName"] = ctx.name_map["PersistentVolumeClaim"].get(n, n)
        if "configMap" in entry and entry["configMap"].get("name"):
            n = entry["configMap"]["name"]
            entry["configMap"]["name"] = ctx.name_map["ConfigMap"].get(n, n)
        if "secret" in entry and entry["secret"].get("secretName"):
            n = entry["secret"]["secretName"]
            entry["secret"]["secretName"] = ctx.name_map["Secret"].get(n, n)
    return vol_map


# ---------------------------------------------------------------------------
# Per-kind handlers -> mutate ctx.values
# ---------------------------------------------------------------------------

def handle_main_container(c: dict, ctx: MicroserviceContext) -> None:
    v = ctx.values
    repo, tag = split_image(c.get("image", ""))
    image = {"repository": repo}
    if tag:
        image["tag"] = tag
    if c.get("imagePullPolicy"):
        image["pullPolicy"] = c["imagePullPolicy"]
    ctx.full_image = image
    # The comprehensive values file omits the tag — that's the minimal
    # override's job (see build_minimal_values), so a day-2 tag bump only
    # ever touches *-values-minimal.yaml, not the auto-generated file.
    v["image"] = {k: val for k, val in image.items() if k != "tag"}

    for k in ("command", "args", "workingDir"):
        if c.get(k):
            v[k] = c[k]
    if c.get("ports"):
        v["ports"] = ports_list_to_map(c["ports"])
    if c.get("env"):
        full_env = remap_env(env_list_to_map(c["env"]), ctx)
        ctx.full_env = full_env
        # Same reasoning as image tag: literal-value env vars are the
        # minimal override's job. valueFrom-based env (ConfigMap/Secret/
        # field/resource refs) stays here — it's structural wiring, not
        # day-2 tuning, and has nowhere else to live.
        structural_env = {k: val for k, val in full_env.items() if "value" not in val or "valueFrom" in val}
        if structural_env:
            v["env"] = structural_env
    if c.get("envFrom"):
        v["envFrom"] = remap_envfrom(envfrom_list_to_map(c["envFrom"]), ctx)
    if c.get("resources"):
        v["resources"] = c["resources"]
    for probe in ("livenessProbe", "readinessProbe", "startupProbe"):
        if c.get(probe):
            v[probe] = c[probe]
    if c.get("lifecycle"):
        v["lifecycle"] = c["lifecycle"]
    if c.get("securityContext"):
        v["securityContext"] = c["securityContext"]
    if c.get("volumeMounts"):
        v["volumeMounts"] = named_list_to_map(c["volumeMounts"])
    if c.get("containerRestartRules"):
        v["containerRestartRules"] = c["containerRestartRules"]
    for flag in ("stdin", "stdinOnce", "tty"):
        if c.get(flag):
            v[flag] = c[flag]
    for k in ("terminationMessagePath", "terminationMessagePolicy"):
        if c.get(k):
            v[k] = c[k]


def handle_workload(doc: dict, ctx: MicroserviceContext, kind: str) -> None:
    ctx.saw_workload = True
    v = ctx.values
    spec = doc.get("spec", {}) or {}
    v.setdefault("workload", {})["type"] = {
        "Deployment": "deployment", "StatefulSet": "statefulset", "DaemonSet": "daemonset",
    }[kind]

    if "replicas" in spec:
        v["replicaCount"] = spec["replicas"]
    if "revisionHistoryLimit" in spec:
        v["revisionHistoryLimit"] = spec["revisionHistoryLimit"]

    if kind == "StatefulSet":
        if spec.get("podManagementPolicy"):
            v["podManagementPolicy"] = spec["podManagementPolicy"]
        vcts = spec.get("volumeClaimTemplates") or []
        if vcts:
            vct_map = {}
            for vct in vcts:
                name = vct["metadata"]["name"]
                vspec = vct.get("spec", {}) or {}
                entry = {"accessModes": vspec.get("accessModes", ["ReadWriteOnce"])}
                size = ((vspec.get("resources") or {}).get("requests") or {}).get("storage")
                if size:
                    entry["size"] = size
                if vspec.get("storageClassName"):
                    entry["storageClassName"] = vspec["storageClassName"]
                if vspec.get("volumeMode"):
                    entry["volumeMode"] = vspec["volumeMode"]
                vct_map[name] = entry
            v["volumeClaimTemplates"] = vct_map

    strategy = spec.get("strategy") or spec.get("updateStrategy")
    if strategy:
        v["strategy"] = strategy

    template = spec.get("template", {}) or {}
    pod_meta = template.get("metadata", {}) or {}
    pod_spec = template.get("spec", {}) or {}

    pod_labels = {
        k: val for k, val in (pod_meta.get("labels") or {}).items()
        if k not in ("pod-template-hash", "app.kubernetes.io/name", "app.kubernetes.io/instance", "app")
    }
    if pod_labels:
        v["podLabels"] = pod_labels
    pod_ann = {k: val for k, val in (pod_meta.get("annotations") or {}).items() if not k.startswith("checksum/")}
    if pod_ann:
        v["podAnnotations"] = pod_ann

    if pod_spec.get("securityContext"):
        v["podSecurityContext"] = pod_spec["securityContext"]

    sa_name = pod_spec.get("serviceAccountName") or pod_spec.get("serviceAccount")
    if sa_name and sa_name != "default":
        final = ctx.name_map["ServiceAccount"].get(sa_name, sa_name)
        # Only default create=True when THIS microservice actually owns a
        # ServiceAccount object under that name (action "own"/"renamed"). If
        # the name is unclaimed here, or claimed by the namespace-shared
        # release ("reference_shared"), this pod is merely a CONSUMER of a
        # ServiceAccount created elsewhere — defaulting create=True in that
        # case would make this release fight the real owner over the same
        # object. Order-independent: claim_actions is fully populated in
        # pass 1, before any doc (ServiceAccount or workload) is handled here.
        action = ctx.claim_actions["ServiceAccount"].get(sa_name)
        v.setdefault("serviceAccount", {})
        v["serviceAccount"]["name"] = final
        v["serviceAccount"].setdefault("create", action not in (None, "reference_shared"))

    for k in ("terminationGracePeriodSeconds", "hostNetwork", "hostIPC", "hostPID",
              "shareProcessNamespace", "priorityClassName", "runtimeClassName",
              "schedulerName", "dnsPolicy", "restartPolicy"):
        if k in pod_spec:
            v[k] = pod_spec[k]
    for k in ("dnsConfig", "nodeSelector", "tolerations", "affinity",
              "topologySpreadConstraints", "imagePullSecrets", "hostAliases",
              "readinessGates", "overhead"):
        if pod_spec.get(k):
            v[k] = pod_spec[k]

    containers = pod_spec.get("containers", []) or []
    if containers:
        handle_main_container(containers[0], ctx)
        for extra in containers[1:]:
            v.setdefault("sidecars", {})[extra["name"]] = {k: val for k, val in extra.items() if k != "name"}
    init_containers = pod_spec.get("initContainers", []) or []
    if init_containers:
        v["initContainers"] = named_list_to_map(init_containers)

    volumes = pod_spec.get("volumes", []) or []
    if volumes:
        v["volumes"] = remap_volumes(named_list_to_map(volumes), ctx)


def build_route_entry(doc: dict, ctx: MicroserviceContext) -> dict:
    spec = doc.get("spec", {}) or {}
    entry = {"enabled": True}
    if spec.get("host"):
        entry["host"] = spec["host"]
    if spec.get("path"):
        entry["path"] = spec["path"]
    tp = (spec.get("port") or {}).get("targetPort")
    if tp:
        entry["targetPort"] = tp
    if spec.get("tls"):
        entry["tls"] = spec["tls"]
    if spec.get("wildcardPolicy") and spec["wildcardPolicy"] != "None":
        entry["wildcardPolicy"] = spec["wildcardPolicy"]
    to_name = (spec.get("to") or {}).get("name")
    if to_name:
        # Remap through the Service name-claiming pass, same as env/envFrom/volumes,
        # in case the target Service got renamed by collision resolution.
        entry["serviceName"] = ctx.name_map["Service"].get(to_name, to_name)
    ann = clean_annotations((doc.get("metadata") or {}).get("annotations"))
    if ann:
        entry["annotations"] = ann
    return entry


def handle_route(doc: dict, ctx: MicroserviceContext, final_name: str) -> None:
    entry = build_route_entry(doc, ctx)
    if not ctx.primary_route_set:
        ctx.primary_route_set = True
        # The primary route's template always targets this release's own
        # fullname Service directly (ignores serviceName) — drop it here so
        # it doesn't look like a meaningful override in the generated values.
        entry.pop("serviceName", None)
        ctx.values["route"] = entry
    else:
        # Extra routes DO honor serviceName (defaults to the fullname Service
        # only when absent) — an extra route fronting a DIFFERENT backend
        # (e.g. an admin Service) depends on this being preserved.
        ctx.values.setdefault("routes", {})[final_name] = entry


def build_service_entry(doc: dict) -> dict:
    spec = doc.get("spec", {}) or {}
    entry = {"type": spec.get("type", "ClusterIP")}
    ports = spec.get("ports") or []
    if ports:
        pmap = {}
        for p in ports:
            name = p.get("name") or f"port-{p['port']}"
            e = {"port": p["port"]}
            if p.get("targetPort") is not None:
                e["targetPort"] = p["targetPort"]
            if p.get("protocol"):
                e["protocol"] = p["protocol"]
            if p.get("nodePort"):
                e["nodePort"] = p["nodePort"]
            pmap[name] = e
        entry["ports"] = pmap
    if spec.get("clusterIP") == "None":
        entry["clusterIP"] = "None"
    if spec.get("type") == "ExternalName" and spec.get("externalName"):
        entry["externalName"] = spec["externalName"]
    if spec.get("externalTrafficPolicy"):
        entry["externalTrafficPolicy"] = spec["externalTrafficPolicy"]
    if spec.get("sessionAffinity") and spec["sessionAffinity"] != "None":
        entry["sessionAffinity"] = spec["sessionAffinity"]
        if spec.get("sessionAffinityConfig"):
            entry["sessionAffinityConfig"] = spec["sessionAffinityConfig"]
    if spec.get("publishNotReadyAddresses") is not None:
        entry["publishNotReadyAddresses"] = spec["publishNotReadyAddresses"]
    if spec.get("selector"):
        entry["selector"] = spec["selector"]
    ann = clean_annotations((doc.get("metadata") or {}).get("annotations"))
    if ann:
        entry["annotations"] = ann
    meta_labels = (doc.get("metadata") or {}).get("labels")
    if meta_labels:
        entry["labels"] = meta_labels
    return entry


def handle_service(doc: dict, ctx: MicroserviceContext, final_name: str) -> None:
    ctx.saw_service = True
    entry = build_service_entry(doc)
    entry["enabled"] = True
    if not ctx.primary_service_set:
        ctx.primary_service_set = True
        entry.pop("selector", None)  # primary service always uses the chart's own selector labels
        ctx.values["service"] = entry
    else:
        ctx.values.setdefault("services", {})[final_name] = entry


def handle_configmap(doc: dict, ctx: MicroserviceContext, name: str) -> None:
    entry = {}
    if doc.get("data"):
        entry["data"] = doc["data"]
    if doc.get("binaryData"):
        entry["binaryData"] = doc["binaryData"]
    meta = doc.get("metadata", {}) or {}
    if meta.get("labels"):
        entry["labels"] = meta["labels"]
    ann = clean_annotations(meta.get("annotations"))
    if ann:
        entry["annotations"] = ann
    ctx.values.setdefault("configMaps", {})[name] = entry


def handle_secret(doc: dict, ctx: MicroserviceContext, name: str) -> None:
    entry = {"type": doc.get("type", "Opaque")}
    if doc.get("data"):
        entry["data"] = doc["data"]
    if doc.get("stringData"):
        entry["stringData"] = doc["stringData"]
    meta = doc.get("metadata", {}) or {}
    if meta.get("labels"):
        entry["labels"] = meta["labels"]
    ann = clean_annotations(meta.get("annotations"))
    if ann:
        entry["annotations"] = ann
    ctx.values.setdefault("secrets", {})[name] = entry


def build_secretstore_entry(doc: dict) -> dict:
    spec = doc.get("spec", {}) or {}
    entry = {}
    for k in ("provider", "retrySettings", "refreshInterval", "conditions"):
        if spec.get(k) is not None:
            entry[k] = spec[k]
    ann = clean_annotations((doc.get("metadata") or {}).get("annotations"))
    if ann:
        entry["annotations"] = ann
    return entry


def handle_secretstore(doc: dict, ctx: MicroserviceContext, name: str) -> None:
    ctx.values.setdefault("secretStores", {})[name] = build_secretstore_entry(doc)


def build_externalsecret_entry(doc: dict, ctx: MicroserviceContext) -> dict:
    spec = doc.get("spec", {}) or {}
    entry = {}
    ssr = spec.get("secretStoreRef") or {}
    if ssr.get("name"):
        ref_kind = ssr.get("kind", "SecretStore")
        ref_name = ssr["name"]
        if ref_kind == "SecretStore":
            # Remap through the same name-claiming pass as ConfigMap/Secret/
            # Service, in case the target SecretStore got renamed by
            # collision resolution. ClusterSecretStore names are deduped
            # globally without renaming, so no remap needed for that kind.
            ref_name = ctx.name_map["SecretStore"].get(ref_name, ref_name)
        entry["secretStoreRef"] = {"name": ref_name, "kind": ref_kind}
    if spec.get("refreshInterval"):
        entry["refreshInterval"] = spec["refreshInterval"]
    target = spec.get("target") or {}
    t = {k: target[k] for k in ("name", "creationPolicy", "deletionPolicy", "template") if target.get(k)}
    if t:
        entry["target"] = t
    if spec.get("data"):
        entry["data"] = spec["data"]
    if spec.get("dataFrom"):
        entry["dataFrom"] = spec["dataFrom"]
    ann = clean_annotations((doc.get("metadata") or {}).get("annotations"))
    if ann:
        entry["annotations"] = ann
    return entry


def handle_externalsecret(doc: dict, ctx: MicroserviceContext, name: str) -> None:
    ctx.values.setdefault("externalSecrets", {})[name] = build_externalsecret_entry(doc, ctx)


def build_clustersecretstore_entry(doc: dict) -> dict:
    spec = doc.get("spec", {}) or {}
    entry = {}
    for k in ("provider", "retrySettings", "refreshInterval", "conditions"):
        if spec.get(k) is not None:
            entry[k] = spec[k]
    return entry


def handle_pvc(doc: dict, ctx: MicroserviceContext, name: str) -> None:
    spec = doc.get("spec", {}) or {}
    entry = {"accessModes": spec.get("accessModes", ["ReadWriteOnce"])}
    size = ((spec.get("resources") or {}).get("requests") or {}).get("storage")
    if size:
        entry["size"] = size
    for k in ("storageClassName", "volumeMode", "volumeName", "selector", "dataSource"):
        if spec.get(k):
            entry[k] = spec[k]
    ann = clean_annotations((doc.get("metadata") or {}).get("annotations"))
    if ann:
        entry["annotations"] = ann
    ctx.values.setdefault("pvc", {})[name] = entry


def handle_networkpolicy(doc: dict, ctx: MicroserviceContext, name: str) -> None:
    spec = doc.get("spec", {}) or {}
    entry = {}
    if "podSelector" in spec:
        entry["podSelector"] = spec["podSelector"]
    if spec.get("policyTypes"):
        entry["policyTypes"] = spec["policyTypes"]
    if spec.get("ingress"):
        entry["ingress"] = spec["ingress"]
    if spec.get("egress"):
        entry["egress"] = spec["egress"]
    ctx.values.setdefault("networkPolicies", {})[name] = entry


def handle_role(doc: dict, ctx: MicroserviceContext, name: str) -> None:
    ctx.values.setdefault("rbac", {}).setdefault("roles", {})[name] = {"rules": doc.get("rules", [])}


def handle_rolebinding(doc: dict, ctx: MicroserviceContext, name: str) -> None:
    role_ref_name = (doc.get("roleRef") or {}).get("name", "")
    final_role = ctx.name_map["Role"].get(role_ref_name, role_ref_name)
    subjects = []
    for s in doc.get("subjects", []) or []:
        s = dict(s)
        s.pop("namespace", None)
        if s.get("kind") == "ServiceAccount":
            s["name"] = ctx.name_map["ServiceAccount"].get(s["name"], s["name"])
        subjects.append(s)
    ctx.values.setdefault("rbac", {}).setdefault("roleBindings", {})[name] = {
        "roleRef": final_role, "subjects": subjects,
    }


def handle_serviceaccount(doc: dict, ctx: MicroserviceContext, name: str) -> None:
    action = ctx.claim_actions["ServiceAccount"].get(name, "own")
    final = ctx.name_map["ServiceAccount"].get(name, name)

    if action == "reference_shared":
        if not ctx.primary_sa_set:
            ctx.primary_sa_set = True
            ctx.values["serviceAccount"] = {"create": False, "name": final}
        return

    if not ctx.primary_sa_set:
        ctx.primary_sa_set = True
        sa = {"create": True, "name": final}
        ann = clean_annotations((doc.get("metadata") or {}).get("annotations"))
        if ann:
            sa["annotations"] = ann
        if "automountServiceAccountToken" in doc:
            sa["automountServiceAccountToken"] = doc["automountServiceAccountToken"]
        ctx.values["serviceAccount"] = sa
    else:
        extra = copy.deepcopy(doc)
        extra["metadata"]["name"] = final
        ctx.extra_deploy.append(dump_yaml(extra))
        ctx.warnings.append(
            f"ServiceAccount/{name}: chart supports one managed ServiceAccount per release; "
            f"extra ServiceAccount emitted via extraDeploy as '{final}'"
        )


def handle_hpa(doc: dict, ctx: MicroserviceContext) -> None:
    spec = doc.get("spec", {}) or {}
    hpa = {"enabled": True}
    if spec.get("minReplicas") is not None:
        hpa["minReplicas"] = spec["minReplicas"]
    if spec.get("maxReplicas") is not None:
        hpa["maxReplicas"] = spec["maxReplicas"]
    if spec.get("metrics"):
        hpa["metrics"] = spec["metrics"]
    if spec.get("behavior"):
        hpa["behavior"] = spec["behavior"]
    ctx.values["hpa"] = hpa


def handle_pdb(doc: dict, ctx: MicroserviceContext) -> None:
    spec = doc.get("spec", {}) or {}
    pdb = {"enabled": True}
    if "minAvailable" in spec:
        pdb["minAvailable"] = spec["minAvailable"]
    elif "maxUnavailable" in spec:
        pdb["maxUnavailable"] = spec["maxUnavailable"]
    ctx.values["pdb"] = pdb


def handle_ingress(doc: dict, ctx: MicroserviceContext) -> None:
    spec = doc.get("spec", {}) or {}
    ing = {"enabled": True}
    if spec.get("ingressClassName"):
        ing["className"] = spec["ingressClassName"]
    hosts = []
    for rule in spec.get("rules", []) or []:
        h = {"host": rule.get("host", "")}
        paths = []
        for p in (rule.get("http", {}) or {}).get("paths", []) or []:
            port_name = (((p.get("backend") or {}).get("service") or {}).get("port") or {}).get("name")
            paths.append({"path": p.get("path", "/"), "pathType": p.get("pathType", "Prefix"), "portName": port_name})
        h["paths"] = paths
        hosts.append(h)
    if hosts:
        ing["hosts"] = hosts
    if spec.get("tls"):
        ing["tls"] = spec["tls"]
    ann = clean_annotations((doc.get("metadata") or {}).get("annotations"))
    if ann:
        ing["annotations"] = ann
    ctx.values["ingress"] = ing


def handle_servicemonitor(doc: dict, ctx: MicroserviceContext) -> None:
    spec = doc.get("spec", {}) or {}
    ep = (spec.get("endpoints") or [{}])[0]
    sm = {"enabled": True}
    for k in ("port", "path", "interval", "scrapeTimeout", "scheme", "tlsConfig", "relabelings", "metricRelabelings"):
        if ep.get(k):
            sm[k] = ep[k]
    meta = doc.get("metadata", {}) or {}
    if meta.get("labels"):
        sm["labels"] = meta["labels"]
    ctx.values["serviceMonitor"] = sm


def handle_vpa(doc: dict, ctx: MicroserviceContext) -> None:
    spec = doc.get("spec", {}) or {}
    vpa = {"enabled": True}
    up = spec.get("updatePolicy", {}) or {}
    if up.get("updateMode"):
        vpa["updateMode"] = up["updateMode"]
    if spec.get("resourcePolicy"):
        vpa["resourcePolicy"] = spec["resourcePolicy"]
    ctx.values["vpa"] = vpa


def handle_cronjob(doc: dict, ctx: MicroserviceContext, name: str) -> None:
    spec = doc.get("spec", {}) or {}
    jt = (spec.get("jobTemplate") or {}).get("spec") or {}
    pod_tpl_spec = (jt.get("template") or {}).get("spec") or {}
    containers = pod_tpl_spec.get("containers", []) or []
    main = containers[0] if containers else {}

    entry = {"schedule": spec.get("schedule", "0 0 * * *")}
    for k in ("concurrencyPolicy", "successfulJobsHistoryLimit", "failedJobsHistoryLimit",
              "suspend", "startingDeadlineSeconds"):
        if spec.get(k) is not None:
            entry[k] = spec[k]

    job_template = {}
    for k in ("backoffLimit", "activeDeadlineSeconds", "ttlSecondsAfterFinished"):
        if jt.get(k) is not None:
            job_template[k] = jt[k]
    if pod_tpl_spec.get("restartPolicy"):
        job_template["restartPolicy"] = pod_tpl_spec["restartPolicy"]
    if main.get("image"):
        repo, tag = split_image(main["image"])
        job_template["image"] = {"repository": repo, "tag": tag}
    for k in ("command", "args"):
        if main.get(k):
            job_template[k] = main[k]
    if main.get("env"):
        job_template["env"] = remap_env(env_list_to_map(main["env"]), ctx)
    if main.get("envFrom"):
        job_template["envFrom"] = remap_envfrom(envfrom_list_to_map(main["envFrom"]), ctx)
    if main.get("resources"):
        job_template["resources"] = main["resources"]
    if main.get("volumeMounts"):
        job_template["volumeMounts"] = named_list_to_map(main["volumeMounts"])
    if pod_tpl_spec.get("volumes"):
        job_template["volumes"] = remap_volumes(named_list_to_map(pod_tpl_spec["volumes"]), ctx)
    entry["jobTemplate"] = job_template

    ann = clean_annotations((doc.get("metadata") or {}).get("annotations"))
    if ann:
        entry["annotations"] = ann
    ctx.values.setdefault("cronjobs", {})[name] = entry


def handle_job(doc: dict, ctx: MicroserviceContext, name: str) -> None:
    spec = doc.get("spec", {}) or {}
    pod_spec = (spec.get("template") or {}).get("spec") or {}
    containers = pod_spec.get("containers", []) or []
    main = containers[0] if containers else {}

    entry = {}
    for k in ("backoffLimit", "activeDeadlineSeconds", "ttlSecondsAfterFinished"):
        if spec.get(k) is not None:
            entry[k] = spec[k]
    if pod_spec.get("restartPolicy"):
        entry["restartPolicy"] = pod_spec["restartPolicy"]
    if main.get("image"):
        repo, tag = split_image(main["image"])
        entry["image"] = {"repository": repo, "tag": tag}
    for k in ("command", "args"):
        if main.get(k):
            entry[k] = main[k]
    if main.get("env"):
        entry["env"] = remap_env(env_list_to_map(main["env"]), ctx)
    if main.get("envFrom"):
        entry["envFrom"] = remap_envfrom(envfrom_list_to_map(main["envFrom"]), ctx)
    if main.get("resources"):
        entry["resources"] = main["resources"]
    if main.get("volumeMounts"):
        entry["volumeMounts"] = named_list_to_map(main["volumeMounts"])
    if pod_spec.get("volumes"):
        entry["volumes"] = remap_volumes(named_list_to_map(pod_spec["volumes"]), ctx)

    ann = clean_annotations((doc.get("metadata") or {}).get("annotations"))
    if ann:
        entry["annotations"] = ann
    ctx.values.setdefault("jobs", {})[name] = entry


# --- cluster-scoped builders -------------------------------------------------

def build_clusterrole_entry(doc: dict) -> dict:
    return {"rules": doc.get("rules", [])}


def build_clusterrolebinding_entry(doc: dict) -> dict:
    subjects = [dict(s) for s in doc.get("subjects", []) or []]
    return {"roleRef": (doc.get("roleRef") or {}).get("name", ""), "subjects": subjects}


def build_storageclass_entry(doc: dict) -> dict:
    entry = {"provisioner": doc.get("provisioner", "")}
    for k in ("reclaimPolicy", "volumeBindingMode", "allowVolumeExpansion",
              "parameters", "mountOptions", "allowedTopologies"):
        if doc.get(k) is not None:
            entry[k] = doc[k]
    return entry


def build_pv_entry(doc: dict) -> dict:
    spec = doc.get("spec", {}) or {}
    entry = {}
    cap = (spec.get("capacity") or {}).get("storage")
    if cap:
        entry["capacity"] = cap
    if spec.get("accessModes"):
        entry["accessModes"] = spec["accessModes"]
    if spec.get("persistentVolumeReclaimPolicy"):
        entry["reclaimPolicy"] = spec["persistentVolumeReclaimPolicy"]
    for k in ("storageClassName", "volumeMode", "mountOptions", "nodeAffinity", "hostPath", "nfs",
              "csi", "local", "iscsi", "fc", "rbd", "gcePersistentDisk", "awsElasticBlockStore",
              "azureDisk", "azureFile"):
        if spec.get(k) is not None:
            entry[k] = spec[k]
    return entry


def build_scc_entry(doc: dict) -> dict:
    entry = {}
    for k in ("priority", "allowPrivilegedContainer", "allowPrivilegeEscalation",
              "defaultAddCapabilities", "allowedCapabilities", "requiredDropCapabilities",
              "runAsUser", "seLinuxContext", "fsGroup", "supplementalGroups", "volumes",
              "allowHostNetwork", "allowHostPorts", "allowHostPID", "allowHostIPC",
              "readOnlyRootFilesystem", "users", "groups", "seccompProfiles",
              "allowedUnsafeSysctls", "forbiddenSysctls"):
        if doc.get(k) is not None:
            entry[k] = doc[k]
    return entry


def handle_cluster_scoped(doc: dict, kind: str, cluster_registry: ClusterRegistry, namespace: str,
                          ms_name: str, cluster_values: dict, warnings: list) -> None:
    name = (doc.get("metadata") or {}).get("name")
    if not name:
        return
    h = content_hash(doc)
    should_emit, note = cluster_registry.claim(kind, name, h, namespace, ms_name)
    if note:
        warnings.append(f"[cluster-scoped] {note}")
    if not should_emit:
        return
    if kind == "ClusterRole":
        cluster_values["rbac"]["clusterRoles"][name] = build_clusterrole_entry(doc)
    elif kind == "ClusterRoleBinding":
        cluster_values["rbac"]["clusterRoleBindings"][name] = build_clusterrolebinding_entry(doc)
    elif kind == "StorageClass":
        cluster_values["storageClasses"][name] = build_storageclass_entry(doc)
    elif kind == "PersistentVolume":
        cluster_values["persistentVolumes"][name] = build_pv_entry(doc)
    elif kind == "SecurityContextConstraints":
        cluster_values["scc"][name] = build_scc_entry(doc)
    elif kind == "ClusterSecretStore":
        cluster_values["clusterSecretStores"][name] = build_clustersecretstore_entry(doc)


# ---------------------------------------------------------------------------
# Microservice orchestration
# ---------------------------------------------------------------------------

def build_microservice(namespace: str, ms_name: str, docs: list[dict], ns_registry: NamespaceRegistry,
                       cluster_registry: ClusterRegistry, cluster_values: dict, warnings: list,
                       owner_label: str) -> MicroserviceContext:
    ctx = MicroserviceContext(namespace=namespace, name=ms_name)

    # Pass 1 — claim raw-name resources first so every reference (env,
    # envFrom, volumes, rbac) can be rewritten consistently in pass 2,
    # regardless of the order objects appear in the source multi-doc file.
    for kind in NS_RAW_NAME_KINDS:
        for doc in docs:
            if doc.get("kind") != kind:
                continue
            if kind == "Secret" and is_auto_sa_secret(doc):
                continue
            name = (doc.get("metadata") or {}).get("name")
            if not name:
                continue
            h = content_hash(doc)
            final, action, note = ns_registry.claim(kind, name, h, owner_label)
            if note:
                ctx.warnings.append(note)
            ctx.name_map[kind][name] = final
            ctx.claim_actions[kind][name] = action

    # Pass 2 — build the actual values.
    for doc in docs:
        kind = doc.get("kind")
        name = (doc.get("metadata") or {}).get("name")

        if kind in WORKLOAD_KINDS:
            handle_workload(doc, ctx, kind)
        elif kind == "Route":
            if ctx.claim_actions["Route"].get(name) != "reference_shared":
                handle_route(doc, ctx, ctx.name_map["Route"][name])
        elif kind == "Service":
            if ctx.claim_actions["Service"].get(name) != "reference_shared":
                handle_service(doc, ctx, ctx.name_map["Service"][name])
        elif kind == "ConfigMap":
            if ctx.claim_actions["ConfigMap"].get(name) != "reference_shared":
                handle_configmap(doc, ctx, ctx.name_map["ConfigMap"][name])
        elif kind == "Secret":
            if is_auto_sa_secret(doc):
                continue
            if ctx.claim_actions["Secret"].get(name) != "reference_shared":
                handle_secret(doc, ctx, ctx.name_map["Secret"][name])
        elif kind == "SecretStore":
            if ctx.claim_actions["SecretStore"].get(name) != "reference_shared":
                handle_secretstore(doc, ctx, ctx.name_map["SecretStore"][name])
        elif kind == "ExternalSecret":
            if ctx.claim_actions["ExternalSecret"].get(name) != "reference_shared":
                handle_externalsecret(doc, ctx, ctx.name_map["ExternalSecret"][name])
        elif kind == "PersistentVolumeClaim":
            if ctx.claim_actions["PersistentVolumeClaim"].get(name) != "reference_shared":
                handle_pvc(doc, ctx, ctx.name_map["PersistentVolumeClaim"][name])
        elif kind == "NetworkPolicy":
            if ctx.claim_actions["NetworkPolicy"].get(name) != "reference_shared":
                handle_networkpolicy(doc, ctx, ctx.name_map["NetworkPolicy"][name])
        elif kind == "Role":
            if ctx.claim_actions["Role"].get(name) != "reference_shared":
                handle_role(doc, ctx, ctx.name_map["Role"][name])
        elif kind == "RoleBinding":
            if ctx.claim_actions["RoleBinding"].get(name) != "reference_shared":
                handle_rolebinding(doc, ctx, ctx.name_map["RoleBinding"][name])
        elif kind == "ServiceAccount":
            handle_serviceaccount(doc, ctx, name)
        elif kind in CLUSTER_SCOPED_KINDS:
            handle_cluster_scoped(doc, kind, cluster_registry, namespace, ms_name, cluster_values, warnings)
        elif kind == "HorizontalPodAutoscaler":
            handle_hpa(doc, ctx)
        elif kind == "PodDisruptionBudget":
            handle_pdb(doc, ctx)
        elif kind == "Ingress":
            handle_ingress(doc, ctx)
        elif kind == "ServiceMonitor":
            handle_servicemonitor(doc, ctx)
        elif kind == "VerticalPodAutoscaler":
            handle_vpa(doc, ctx)
        elif kind == "CronJob":
            handle_cronjob(doc, ctx, name)
        elif kind == "Job":
            handle_job(doc, ctx, name)
        else:
            ctx.extra_deploy.append(dump_yaml(doc))
            ctx.warnings.append(f"Unrecognized kind '{kind}' ({name}) passed through via extraDeploy")

    if not ctx.saw_workload:
        ctx.values.setdefault("workload", {})["type"] = "none"
    if not ctx.saw_service and "service" not in ctx.values:
        ctx.values["service"] = {"enabled": False}

    if ctx.extra_deploy:
        ctx.values["extraDeploy"] = ctx.extra_deploy

    return ctx


def build_minimal_values(ctx: MicroserviceContext) -> dict:
    minimal: dict = {}
    img = {k: v for k, v in ctx.full_image.items() if k in ("repository", "tag")}
    if img:
        minimal["image"] = img
    literal_env = {k: v for k, v in ctx.full_env.items() if "value" in v and "valueFrom" not in v}
    if literal_env:
        minimal["env"] = literal_env
    return minimal


def write_microservice_output(namespace_dir: Path, ms_name: str, namespace: str,
                              ctx: MicroserviceContext) -> None:
    """
    Full and minimal values are written as FLAT files — no per-microservice
    subdirectory — in two PARALLEL trees (values/ and values-minimal/) under
    the namespace's own output directory. A tiny releases/<ms_name>.yaml
    pointer file is written alongside purely so an ArgoCD ApplicationSet git
    "files" generator can enumerate microservices without a directory per
    release; it is not itself a values file.
    """
    values_dir = namespace_dir / VALUES_DIR_NAME
    values_minimal_dir = namespace_dir / VALUES_MINIMAL_DIR_NAME
    releases_dir = namespace_dir / RELEASES_DIR_NAME
    values_dir.mkdir(parents=True, exist_ok=True)
    values_minimal_dir.mkdir(parents=True, exist_ok=True)
    releases_dir.mkdir(parents=True, exist_ok=True)

    minimal = build_minimal_values(ctx)
    header_full = (
        f"# Auto-generated by convert_to_universal_chart.py — DO NOT EDIT BY HAND.\n"
        f"# Source: namespaces/{namespace}/{ms_name}.yaml\n"
        f"# Re-run the converter to regenerate after the source manifest changes.\n\n"
    )
    header_min = (
        f"# Auto-generated MINIMAL override for '{ms_name}' — image + literal env only.\n"
        f"# This is the client's single source of truth for day-2 tuning; safe to hand-edit\n"
        f"# and applied LAST (highest precedence) over {ms_name}-values.yaml.\n\n"
    )
    (values_dir / f"{ms_name}-values.yaml").write_text(header_full + dump_yaml(ctx.values), encoding="utf-8")
    (values_minimal_dir / f"{ms_name}-values-minimal.yaml").write_text(
        header_min + dump_yaml(minimal), encoding="utf-8"
    )
    (releases_dir / f"{ms_name}.yaml").write_text(dump_yaml({"release": ms_name}), encoding="utf-8")


# ---------------------------------------------------------------------------
# ArgoCD ApplicationSet generation
# ---------------------------------------------------------------------------

def common_ignore_differences() -> list[dict]:
    """
    OpenShift/Kubernetes admission mutates several fields on live objects
    that Helm's desired manifest never sets (SCC-assigned runAsUser/fsGroup/
    seLinuxOptions when a pod doesn't pin its own, controller-populated
    ServiceAccount secrets/imagePullSecrets). Without this, ArgoCD's
    self-heal fights the cluster's own admission controllers and the
    Application flips OutOfSync -> Synced every reconcile. StatefulSet
    volumeClaimTemplates are immutable post-creation, so a spec diff there
    can never actually be applied — ignore it too instead of looping forever.
    """
    security_context_paths = [
        ".spec.template.spec.securityContext.runAsUser",
        ".spec.template.spec.securityContext.runAsGroup",
        ".spec.template.spec.securityContext.fsGroup",
        ".spec.template.spec.securityContext.seLinuxOptions",
        ".spec.template.spec.containers[]?.securityContext.runAsUser",
        ".spec.template.spec.containers[]?.securityContext.capabilities",
    ]
    return [
        {"group": "apps", "kind": "Deployment", "jqPathExpressions": security_context_paths},
        {"group": "apps", "kind": "StatefulSet",
         "jqPathExpressions": security_context_paths + [".spec.volumeClaimTemplates"]},
        {"group": "apps", "kind": "DaemonSet", "jqPathExpressions": security_context_paths},
        {"group": "", "kind": "ServiceAccount", "jsonPointers": ["/secrets", "/imagePullSecrets"]},
    ]


def build_applicationset(namespace: str, chart_repo_url: str, chart_path: str, chart_revision: str,
                         values_repo_url: str, values_revision: str) -> dict:
    values_base = f"{namespace}/{VALUES_DIR_NAME}"
    values_minimal_base = f"{namespace}/{VALUES_MINIMAL_DIR_NAME}"
    releases_base = f"{namespace}/{RELEASES_DIR_NAME}"
    return {
        "apiVersion": "argoproj.io/v1alpha1",
        "kind": "ApplicationSet",
        "metadata": {
            "name": f"{namespace}-microservices",
            "namespace": "argocd",
            "annotations": {
                "generated-by": "convert_to_universal_chart.py",
            },
        },
        "spec": {
            # A "files" generator (not "directories") since values/values-minimal
            # are flat — one entry per tiny releases/<ms>.yaml pointer file,
            # whose only content is {release: <ms>}. {{release}} below comes
            # from that file's own content, not from a path segment.
            "generators": [
                {"git": {"repoURL": values_repo_url, "revision": values_revision,
                         "files": [{"path": f"{releases_base}/*.yaml"}]}}
            ],
            "template": {
                "metadata": {
                    "name": f"{namespace}-{{{{release}}}}",
                    "labels": {"namespace": namespace, "managed-by": "universal-chart-converter"},
                    "annotations": {"argocd.argoproj.io/sync-wave": "0"},
                },
                "spec": {
                    "project": "default",
                    "sources": [
                        {
                            "repoURL": chart_repo_url,
                            "targetRevision": chart_revision,
                            "path": chart_path,
                            "helm": {
                                "valueFiles": [
                                    f"$values/{values_base}/{{{{release}}}}-values.yaml",
                                    f"$values/{values_minimal_base}/{{{{release}}}}-values-minimal.yaml",
                                ],
                            },
                        },
                        {"repoURL": values_repo_url, "targetRevision": values_revision, "ref": "values"},
                    ],
                    "destination": {"server": "https://kubernetes.default.svc", "namespace": namespace},
                    "syncPolicy": {
                        "automated": {"prune": True, "selfHeal": True},
                        "syncOptions": ["CreateNamespace=true", "ServerSideApply=true"],
                    },
                    "ignoreDifferences": common_ignore_differences(),
                },
            },
        },
    }


def build_cluster_shared_application(namespace: str, chart_repo_url: str, chart_path: str, chart_revision: str,
                                     values_repo_url: str, values_revision: str) -> dict:
    return {
        "apiVersion": "argoproj.io/v1alpha1",
        "kind": "Application",
        "metadata": {"name": "cluster-shared-resources", "namespace": "argocd"},
        "spec": {
            "project": "default",
            "sources": [
                {
                    "repoURL": chart_repo_url,
                    "targetRevision": chart_revision,
                    "path": chart_path,
                    "helm": {"valueFiles": [
                        f"$values/{CLUSTER_SHARED_DIR_NAME}/{VALUES_DIR_NAME}/cluster-shared-values.yaml"
                    ]},
                },
                {"repoURL": values_repo_url, "targetRevision": values_revision, "ref": "values"},
            ],
            "destination": {"server": "https://kubernetes.default.svc", "namespace": namespace},
            "syncPolicy": {
                "automated": {"prune": True, "selfHeal": True},
                "syncOptions": ["CreateNamespace=true", "ServerSideApply=true"],
            },
        },
    }


# ---------------------------------------------------------------------------
# Render-time verification — the real proof the output is conflict-free
# ---------------------------------------------------------------------------
# Rendering each release in isolation only proves its *values* parse. The
# real proof that nothing will fight over ownership once every release is
# `helm install`ed is rendering them ALL and checking, on the actual
# manifests `helm template` produces, that no two releases claim the same
# (kind, namespace, name) — and, for cluster-scoped kinds, no two releases in
# the WHOLE run claim the same (kind, name) regardless of namespace.

def helm_template(chart: Path, release: str, namespace: str, value_files: list[Path]) -> list[dict]:
    cmd = ["helm", "template", release, str(chart), "--namespace", namespace]
    for vf in value_files:
        cmd += ["-f", str(vf)]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"helm template failed for {release}: {result.stderr}")
    return [d for d in yaml.safe_load_all(result.stdout) if d]


def verify_no_conflicts(chart: Path, output_dir: Path) -> tuple[int, list[str]]:
    """Renders every generated release and returns (releases_rendered, conflicts).

    Each top-level entry under output_dir (other than NON_NAMESPACE_OUTPUT_DIRS
    and cluster-shared) is a namespace directory containing the two PARALLEL,
    FLAT values/ and values-minimal/ trees written by write_microservice_output
    — full values are discovered by globbing values/*-values.yaml, and the
    matching minimal override (if it exists) is looked up at
    values-minimal/<release>-values-minimal.yaml.
    """
    ns_claims: dict[str, dict[tuple[str, str], str]] = defaultdict(dict)
    cluster_claims: dict[tuple[str, str], str] = {}
    conflicts: list[str] = []
    rendered = 0

    for ns_dir in sorted(p for p in output_dir.iterdir() if p.is_dir()):
        namespace = ns_dir.name
        if namespace == CLUSTER_SHARED_DIR_NAME or namespace in NON_NAMESPACE_OUTPUT_DIRS:
            continue
        values_dir = ns_dir / VALUES_DIR_NAME
        values_minimal_dir = ns_dir / VALUES_MINIMAL_DIR_NAME
        if not values_dir.is_dir():
            continue
        for vf in sorted(values_dir.glob("*-values.yaml")):
            release = vf.name[:-len("-values.yaml")]
            value_files = [vf]
            minimal_vf = values_minimal_dir / f"{release}-values-minimal.yaml"
            if minimal_vf.exists():
                value_files.append(minimal_vf)
            docs = helm_template(chart, release, namespace, value_files)
            rendered += 1
            for doc in docs:
                kind = doc.get("kind")
                name = (doc.get("metadata") or {}).get("name")
                if not kind or not name:
                    continue
                if kind in CLUSTER_SCOPED_KINDS:
                    key = (kind, name)
                    if key in cluster_claims and cluster_claims[key] != release:
                        conflicts.append(f"CLUSTER CONFLICT: {kind}/{name} claimed by both "
                                         f"'{cluster_claims[key]}' and '{namespace}/{release}'")
                    else:
                        cluster_claims[key] = release
                else:
                    key = (kind, name)
                    if key in ns_claims[namespace] and ns_claims[namespace][key] != release:
                        conflicts.append(f"NAMESPACE CONFLICT in '{namespace}': {kind}/{name} claimed by both "
                                         f"'{ns_claims[namespace][key]}' and '{release}'")
                    else:
                        ns_claims[namespace][key] = release

    cluster_shared_dir = output_dir / CLUSTER_SHARED_DIR_NAME / VALUES_DIR_NAME
    if cluster_shared_dir.exists():
        vf = cluster_shared_dir / "cluster-shared-values.yaml"
        docs = helm_template(chart, CLUSTER_SHARED_DIR_NAME, "platform-shared", [vf])
        rendered += 1
        for doc in docs:
            kind, name = doc.get("kind"), (doc.get("metadata") or {}).get("name")
            if kind in CLUSTER_SCOPED_KINDS and name:
                key = (kind, name)
                if key in cluster_claims and cluster_claims[key] != CLUSTER_SHARED_DIR_NAME:
                    conflicts.append(f"CLUSTER CONFLICT: {kind}/{name} claimed by both "
                                     f"'{cluster_claims[key]}' and '{CLUSTER_SHARED_DIR_NAME}'")
                else:
                    cluster_claims[key] = CLUSTER_SHARED_DIR_NAME

    print(f"Rendered {rendered} releases.")
    print(f"Namespaced resource claims checked: {sum(len(v) for v in ns_claims.values())}")
    print(f"Cluster-scoped resource claims checked: {len(cluster_claims)}")
    return rendered, conflicts


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--input", default="namespaces", help="root folder containing <namespace>/<microservice>.yaml")
    ap.add_argument("--output", default="output", help="output folder for values/applicationsets/report")
    ap.add_argument("--chart-repo-url", default="https://git.example.com/gitops/universal-chart.git")
    ap.add_argument("--chart-path", default="Universal-chart")
    ap.add_argument("--chart-revision", default="main")
    ap.add_argument("--values-repo-url", default="https://git.example.com/gitops/microservices-values.git")
    ap.add_argument("--values-revision", default="main")
    ap.add_argument("--cluster-shared-namespace", default="platform-shared")
    ap.add_argument("--chart", default="../Universal-chart",
                     help="path to the Universal Chart, used for the render-verification step")
    ap.add_argument("--skip-verify", action="store_true",
                     help="skip rendering every release with `helm template` to prove no ownership conflicts")
    args = ap.parse_args()

    input_dir = Path(args.input)
    output_dir = Path(args.output)
    appset_dir = output_dir / "applicationsets"
    report_dir = output_dir / "report"

    if not input_dir.is_dir():
        sys.exit(f"Input directory not found: {input_dir}")

    cluster_registry = ClusterRegistry()
    cluster_values = {"rbac": {"clusterRoles": {}, "clusterRoleBindings": {}},
                       "storageClasses": {}, "persistentVolumes": {}, "scc": {},
                       "clusterSecretStores": {}}
    all_warnings: list[str] = []
    summary = {"namespaces": {}, "totals": {"microservices": 0, "warnings": 0}}

    namespace_dirs = sorted(p for p in input_dir.iterdir() if p.is_dir())
    for ns_dir in namespace_dirs:
        namespace = ns_dir.name
        out_ns_dir = output_dir / namespace
        ns_registry = NamespaceRegistry(namespace)
        ns_warnings: list[str] = []
        ms_count = 0

        shared_path = ns_dir / "shared.yaml"
        if shared_path.exists():
            shared_docs = filter_transient([sanitize_object(d) for d in load_multidoc(shared_path)])
            shared_ctx = build_microservice(namespace, SHARED_DIR_NAME, shared_docs, ns_registry, cluster_registry,
                                            cluster_values, ns_warnings, owner_label="_shared")
            write_microservice_output(out_ns_dir, SHARED_DIR_NAME, namespace, shared_ctx)

        for ms_file in sorted(ns_dir.glob("*.yaml")):
            if ms_file.name == "shared.yaml":
                continue
            ms_name = ms_file.stem
            docs = filter_transient([sanitize_object(d) for d in load_multidoc(ms_file)])
            ctx = build_microservice(namespace, ms_name, docs, ns_registry, cluster_registry, cluster_values,
                                     ns_warnings, owner_label=ms_name)
            write_microservice_output(out_ns_dir, ms_name, namespace, ctx)
            ms_count += 1
            all_warnings.extend(f"[{namespace}/{ms_name}] {w}" for w in ctx.warnings)

        all_warnings.extend(f"[{namespace}] {w}" for w in ns_warnings)

        appset = build_applicationset(namespace, args.chart_repo_url, args.chart_path, args.chart_revision,
                                      args.values_repo_url, args.values_revision)
        appset_dir.mkdir(parents=True, exist_ok=True)
        (appset_dir / f"{namespace}-applicationset.yaml").write_text(dump_yaml(appset), encoding="utf-8")

        summary["namespaces"][namespace] = {"microservices": ms_count, "warnings": len(ns_warnings)}
        summary["totals"]["microservices"] += ms_count

    if any(cluster_values[k] for k in ("storageClasses", "persistentVolumes", "scc", "clusterSecretStores")) or \
       cluster_values["rbac"]["clusterRoles"] or cluster_values["rbac"]["clusterRoleBindings"]:
        cluster_dir = output_dir / CLUSTER_SHARED_DIR_NAME / VALUES_DIR_NAME
        cluster_dir.mkdir(parents=True, exist_ok=True)
        header = (
            "# Auto-generated by convert_to_universal_chart.py\n"
            "# Cluster-scoped resources deduplicated across the ENTIRE run — deploy exactly ONCE.\n"
            "workload:\n  type: none\nservice:\n  enabled: false\n\n"
        )
        (cluster_dir / "cluster-shared-values.yaml").write_text(header + dump_yaml(cluster_values), encoding="utf-8")
        app = build_cluster_shared_application(args.cluster_shared_namespace, args.chart_repo_url, args.chart_path,
                                               args.chart_revision, args.values_repo_url, args.values_revision)
        appset_dir.mkdir(parents=True, exist_ok=True)
        (appset_dir / "cluster-shared-application.yaml").write_text(dump_yaml(app), encoding="utf-8")

    summary["totals"]["warnings"] = len(all_warnings)
    report_dir.mkdir(parents=True, exist_ok=True)
    (report_dir / "conversion_report.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")
    (report_dir / "conflicts_and_warnings.txt").write_text(
        ("\n".join(all_warnings) + "\n") if all_warnings else "No conflicts detected.\n", encoding="utf-8"
    )

    print(f"Converted {summary['totals']['microservices']} microservices across {len(namespace_dirs)} namespaces.")
    print(f"Auto-resolved conflicts / warnings: {summary['totals']['warnings']} "
          f"(see {report_dir / 'conflicts_and_warnings.txt'})")
    print(f"Values written under:          {output_dir}/<namespace>/{VALUES_DIR_NAME}/")
    print(f"Minimal values written under:  {output_dir}/<namespace>/{VALUES_MINIMAL_DIR_NAME}/")
    print(f"ApplicationSets written under: {appset_dir}")

    if args.skip_verify:
        print("Skipping render-verification (--skip-verify).")
        return

    chart = Path(args.chart)
    if not chart.is_dir():
        sys.exit(f"\n--chart path not found: {chart} "
                  f"(pass --chart to point at the Universal Chart, or --skip-verify to skip this step)")

    print(f"\nVerifying against {chart} — rendering every release with `helm template`...")
    try:
        rendered, conflicts = verify_no_conflicts(chart, output_dir)
    except RuntimeError as e:
        sys.exit(f"\n{e}")

    render_report = report_dir / "render_conflicts.txt"
    render_report.write_text(
        ("\n".join(conflicts) + "\n") if conflicts else "No duplicate resource ownership detected.\n",
        encoding="utf-8",
    )
    if conflicts:
        print(f"\n{len(conflicts)} REAL RENDER-TIME CONFLICT(S) FOUND (see {render_report}):")
        for c in conflicts:
            print(f"  - {c}")
        sys.exit(1)
    print(f"\nNo duplicate resource ownership detected across any of the {rendered} rendered releases. Conflict-free.")


if __name__ == "__main__":
    main()
#